FROM node:alpine

RUN mkdir -p /usr/src/{{ app_name }} && chown -R node:node /usr/src/{{ app_name }}

WORKDIR /usr/src/{{ app_name }}

COPY package.json yarn.lock ./

USER node

RUN yarn install --pure-lockfile

COPY --chown=node:node . .

EXPOSE 3000
